version: '3.9'
services:
  mongo_db:
    image: mongo:latest
    container_name: db_container
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data_container:/data/db

  user_api:
    build:
      context: ./user-interaction
      dockerfile: Dockerfile
    command: yarn start:grpc
    ports:
      - '9000:9000'
    environment:
      DB_URI: mongodb://mongo_db:27017/user-interaction
    volumes:
      - .:/usr/user_api/
      - /usr/user_api/node_modules
    depends_on:
      - mongo_db

  contents_api:
    build:
      context: ./contents
      dockerfile: Dockerfile
    ports:
      - '9001:9001'
    environment:
      DB_URI: mongodb://mongo_db:27017/contents
    volumes:
      - .:/usr/contents_api/
      - /usr/contents_api/node_modules
    depends_on:
      - mongo_db

  api_gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - .:/usr/api_gateway/
      - /usr/api_gateway/node_modules
    depends_on:
      - mongo_db
      - user_api
      - contents_api

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    command: yarn start
    ports:
      - '3000:3000'
    environment:
      REACT_APP_SERVER: http://localhost:5000
    volumes:
      - .:/usr/frontend/
      - /usr/frontend/node_modules

volumes:
  mongodb_data_container:
